_target_: torch.utils.data.DataLoader

dataset:
  _target_: projects.detection.datasets.k_water.KWATER
  mode: train
  dataset_info:
    total_fold: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    val_fold: [ 8 ]
    test_fold: [ 9 ]
    dataset_size_scale_factor: 1.0
batch_size: 4
num_workers: 0
pin_memory: True
prefetch_factor: 2
drop_last: False
